# generated by datamodel-codegen:
#   filename:  library.json
#   timestamp: 2026-03-20T14:53:59+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Items(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class Return(BaseModel):
    type: str
    items: Items


class ListBooks(BaseModel):
    method: str
    path: str
    return_: Return = Field(..., alias='return')


class Operations(BaseModel):
    listBooks: ListBooks


class Id(BaseModel):
    type: str


class Title(BaseModel):
    type: str


class Properties(BaseModel):
    id: Id
    title: Title


class Book(BaseModel):
    type: str
    properties: Properties


class Definitions(BaseModel):
    Book_1: Book = Field(..., alias='Book')


class Model(BaseModel):
    operations: Operations
    definitions: Definitions
